use paint;
CREATE TABLE words(
	word varchar(255) unique not null
);
insert into words(word) values ("Bird");
insert into words(word) values ("Mouse");
insert into words(word) values ("Whale");
insert into words(word) values ("Jacket");
insert into words(word) values ("Shirt");
insert into words(word) values ("Hippo");
insert into words(word) values ("Beach");
insert into words(word) values ("Egg");
insert into words(word) values ("Cookie");
insert into words(word) values ("Cheese");
insert into words(word) values ("Skip");
insert into words(word) values ("Drum");
insert into words(word) values ("Worm");
insert into words(word) values ("Spider");
insert into words(word) values ("Bridge");
insert into words(word) values ("Bell");
insert into words(word) values ("Safe");
insert into words(word) values ("Picnic");
insert into words(word) values ("Shrink");
insert into words(word) values ("Ray");
insert into words(word) values ("Leak");
insert into words(word) values ("Deep");
insert into words(word) values ("Tiptoe");
insert into words(word) values ("Hurdle");
insert into words(word) values ("Knight");
insert into words(word) values ("Cloak");
insert into words(word) values ("Bedbug");
insert into words(word) values ("Hot Tub");
insert into words(word) values ("Firefighter");
insert into words(word) values ("Charger");
insert into words(word) values ("Bunny");
insert into words(word) values ("Jellyfish");
insert into words(word) values ("Sweater");
insert into words(word) values ("Picnic");
insert into words(word) values ("Shrink");
insert into words(word) values ("Ray");
insert into words(word) values ("Leak");
insert into words(word) values ("Deep");
insert into words(word) values ("Tiptoe");
insert into words(word) values ("Hurdle");
insert into words(word) values ("Knight");
insert into words(word) values ("Cloak");